### ISSUE TITLE
21 Factorial exception.

### ISSUE THREAD

**Issue by yuktikhurana** [osifoanosike/basicruby#11]
1. Not working

**Comment by osifoanosike** [comment]
Fixed

**Comment by yuktikhurana** [comment]
1.Still not working for negative numbers
2.Number regex in main.rb is wrong

**Comment by osifoanosike** [comment]
fixed.
Corrected Regex
Added meaningful error messages

**Comment by yuktikhurana** [comment]
1. When i enter a negative number i get the message "Non-integer value entered .Try again"
2. For exceptions please use e.message

**Comment by osifoanosike** [comment]
Exceptions handling corrected. Fixed

**Comment by yuktikhurana** [comment]
you're raising bad argument error and resuing argument error. User should just see a message and not the  where the exception occurred. Please correct it.

**Comment by osifoanosike** [comment]
ok, i.e i should handle the exception in main.rb? or i should rescue BadArgumentError?

**Comment by yuktikhurana** [comment]
The exception that you're rescuing is wrong. Yes, you're rescuing at the correct place, just need to rescue BadArgumentError and simply show e.message.

**Comment by osifoanosike** [comment]
ok. Fixed

**Comment by yuktikhurana** [comment]
very good :+1:
