### ISSUE TITLE
1. Ocurrence Hash

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/basicruby#14]
Question 1

**Comment by abhishekjain16** [comment]
1. method name should be count_char_occurences rather than check_char_occurrences.
2. Not sure if we require grep method to check characters here, we simply need to update counter with each character.
3. Also, as we are initialising hash with 0, we dont need to set to 1 for character occurring for the first time, we can just increment it.

**Comment by osifoanosike** [comment]
Fixed. I hope i got the correction right @nos 2

**Comment by abhishekjain16** [comment]
if freq.has_key?(/#{xter}/i)
          (freq[xter] = freq[xter] + 1)
        else
          freq[xter] += 1
        end
This is still not needed, as we already have initialized hash,
freq[xter] += 1 will suffice

**Comment by osifoanosike** [comment]
Thanks for the correction. Fixed
