### ISSUE TITLE
23. CSV

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/basicruby#20]

**Comment by jatin-baweja** [comment]
1. Please do not use absolute file paths, use relative file paths so that code can be run on other systems.
2. Please correct indentation.
3. You can output the result to a text file.
4. `group_by` can be used to group employees.

**Comment by osifoanosike** [comment]
Issues have been fixed.

**Comment by jatin-baweja** [comment]
1. Indentation still not correct.
2. Using for-in loop for details. Is there an alternate way you can use to iterate on details?
3. FileOps class could be renamed as FileOperation

**Comment by osifoanosike** [comment]
Corrections have been made. Also indented the details in the output file.
